package org.baswell.routes;

enum MethodRouteParameterType
{
  ROUTE_PATH,
  ROUTE_PARAMETER,
  ROUTE_PARAMETERS,
  SERVLET_REQUEST,
  SERVLET_RESPONSE,
  REQUEST_PATH,
  REQUEST_PARAMETERS,
  PARAMETER_LIST_MAP,
  PARAMETER_MAP,
  SESSION,
  FORMAT,
  URL;
}
